In [1]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("HousePrices.csv")

In [4]:
data

Id  Dwell_Type Zone_Class  LotFrontage  LotArea Road_Type Alley  \
0       1          60         RL         65.0     8450      Pave   NaN   
1       2          20         RL         80.0     9600      Pave   NaN   
2       3          60         RL         68.0    11250      Pave   NaN   
3       4          70         RL         60.0     9550      Pave   NaN   
4       5          60         RL         84.0    14260      Pave   NaN   
...   ...         ...        ...          ...      ...       ...   ...   
2068  942          60         RL          NaN     8755      Pave   NaN   
2069  943          90         RL         63.0     7711      Pave   NaN   
2070  944          90         RL        313.0    25000      Pave   NaN   
2071  945          20         RL         52.0    14375      Pave   NaN   
2072  946          50         RM         98.0     8820      Pave   NaN   

     Property_Shape LandContour Utilities  ... PoolArea PoolQC  Fence  \
0               Reg         Lvl    AllPub  ...        0    NaN    NaN   
1               Reg         Lvl    AllPub  ...        0    NaN    NaN   
2               IR1         Lvl    AllPub  ...        0    NaN    NaN   
3               IR1         Lvl    AllPub  ...        0    NaN    NaN   
4               IR1         Lvl    AllPub  ...        0    NaN    NaN   
...             ...         ...       ...  ...      ...    ...    ...   
2068            IR1         Lvl    AllPub  ...        0    NaN  GdPrv   
2069            IR1         Lvl    AllPub  ...        0    NaN    NaN   
2070            Reg         Low    AllPub  ...        0    NaN    NaN   
2071            IR1         Lvl    NoSeWa  ...        0    NaN    NaN   
2072            Reg         Lvl    AllPub  ...        0    NaN   MnWw   

     MiscFeature MiscVal MoSold YrSold  SaleType  SaleCondition  \
0            NaN       0      2   2008        WD         Normal   
1            NaN       0      5   2007        WD         Normal   
2            NaN       0      9   2008        WD         Normal   
3            NaN       0      2   2006        WD        Abnorml   
4            NaN       0     12   2008        WD         Normal   
...          ...     ...    ...    ...       ...            ...   
2068         NaN       0      6   2009        WD         Normal   
2069         NaN       0      8   2007       Oth        Abnorml   
2070         NaN       0      6   2007        WD         Normal   
2071         NaN       0      1   2009       COD        Abnorml   
2072         NaN       0      9   2009        WD         Normal   

      Property_Sale_Price  
0                  208500  
1                  181500  
2                  223500  
3                  140000  
4                  250000  
...                   ...  
2068               214000  
2069               150000  
2070               143000  
2071               137500  
2072               124900  

[2073 rows x 81 columns]

In [5]:
data.isnull().sum()

Id                       0
Dwell_Type               0
Zone_Class               0
LotFrontage            320
LotArea                  0
                      ... 
MoSold                   0
YrSold                   0
SaleType                 0
SaleCondition            0
Property_Sale_Price      0
Length: 81, dtype: int64

In [6]:
data.isnull()

Id  Dwell_Type  Zone_Class  LotFrontage  LotArea  Road_Type  Alley  \
0     False       False       False        False    False      False   True   
1     False       False       False        False    False      False   True   
2     False       False       False        False    False      False   True   
3     False       False       False        False    False      False   True   
4     False       False       False        False    False      False   True   
...     ...         ...         ...          ...      ...        ...    ...   
2068  False       False       False         True    False      False   True   
2069  False       False       False        False    False      False   True   
2070  False       False       False        False    False      False   True   
2071  False       False       False        False    False      False   True   
2072  False       False       False        False    False      False   True   

      Property_Shape  LandContour  Utilities  ...  PoolArea  PoolQC  Fence  \
0              False        False      False  ...     False    True   True   
1              False        False      False  ...     False    True   True   
2              False        False      False  ...     False    True   True   
3              False        False      False  ...     False    True   True   
4              False        False      False  ...     False    True   True   
...              ...          ...        ...  ...       ...     ...    ...   
2068           False        False      False  ...     False    True  False   
2069           False        False      False  ...     False    True   True   
2070           False        False      False  ...     False    True   True   
2071           False        False      False  ...     False    True   True   
2072           False        False      False  ...     False    True  False   

      MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0            True    False   False   False     False          False   
1            True    False   False   False     False          False   
2            True    False   False   False     False          False   
3            True    False   False   False     False          False   
4            True    False   False   False     False          False   
...           ...      ...     ...     ...       ...            ...   
2068         True    False   False   False     False          False   
2069         True    False   False   False     False          False   
2070         True    False   False   False     False          False   
2071         True    False   False   False     False          False   
2072         True    False   False   False     False          False   

      Property_Sale_Price  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
2068                False  
2069                False  
2070                False  
2071                False  
2072                False  

[2073 rows x 81 columns]

In [7]:
miss_val = data.columns[data.isnull().any()]
data[miss_val].isnull().sum()

LotFrontage      320
Alley           1944
MasVnrType        14
MasVnrArea        14
BsmtQual          59
BsmtCond          59
BsmtExposure      61
BsmtFinType1      59
BsmtFinType2      60
Electrical         1
FireplaceQu      988
GarageType       113
GarageYrBlt      113
GarageFinish     113
GarageQual       113
GarageCond       113
PoolQC          2065
Fence           1669
MiscFeature     1993
dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073 entries, 0 to 2072
Data columns (total 81 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Id                   2073 non-null   int64  
 1   Dwell_Type           2073 non-null   int64  
 2   Zone_Class           2073 non-null   object 
 3   LotFrontage          1753 non-null   float64
 4   LotArea              2073 non-null   int64  
 5   Road_Type            2073 non-null   object 
 6   Alley                129 non-null    object 
 7   Property_Shape       2073 non-null   object 
 8   LandContour          2073 non-null   object 
 9   Utilities            2073 non-null   object 
 10  LotConfig            2073 non-null   object 
 11  LandSlope            2073 non-null   object 
 12  Neighborhood         2073 non-null   object 
 13  Condition1           2073 non-null   object 
 14  Condition2           2073 non-null   object 
 15  Dwelling_Type        2073 non-null   o

In [9]:
data['LotFrontage'].fillna((data['LotFrontage'].mean()),inplace=True)

In [10]:
data['BsmtUnfSF'].fillna(data['BsmtUnfSF'].mean(),inplace=True)
data['LotArea'].fillna(data['LotArea'].mean(),inplace=True)
data['OverallQual'].fillna(data['OverallQual'].mean(),inplace=True)
data['OverallCond'].fillna(data['OverallCond'].mean(),inplace=True)
data['MasVnrArea'].fillna(data['MasVnrArea'].mean(),inplace=True)

In [11]:
data.isnull().sum()

Id                     0
Dwell_Type             0
Zone_Class             0
LotFrontage            0
LotArea                0
                      ..
MoSold                 0
YrSold                 0
SaleType               0
SaleCondition          0
Property_Sale_Price    0
Length: 81, dtype: int64

In [12]:
x1 = data[['Dwell_Type','LotFrontage', 'LotArea','OverallQual','OverallCond','MasVnrArea',
'BsmtFinSF1','BsmtUnfSF','TotalBsmtSF','1stFlrSF','2ndFlrSF','GrLivArea','GarageArea',
'WoodDeckSF', 'OpenPorchSF']]  #independent
y1 = data['Property_Sale_Price']    #dependent
print(x1,y1)

      Dwell_Type  LotFrontage  LotArea  OverallQual  OverallCond  MasVnrArea  \
0             60    65.000000     8450            7            5       196.0   
1             20    80.000000     9600            6            8         0.0   
2             60    68.000000    11250            7            5       162.0   
3             70    60.000000     9550            7            5         0.0   
4             60    84.000000    14260            8            5       350.0   
...          ...          ...      ...          ...          ...         ...   
2068          60    72.056475     8755            8            4       298.0   
2069          90    63.000000     7711            6            9         0.0   
2070          90   313.000000    25000            4            6         0.0   
2071          20    52.000000    14375            9            6       541.0   
2072          50    98.000000     8820            9            9         0.0   

      BsmtFinSF1  BsmtUnfSF  TotalBsmtS

In [13]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x1,y1)

LinearRegression()

In [15]:
model.score(x1,y1)

0.7301484228992423

In [16]:
model.coef_

array([-8.92284965e+00,  1.36022005e+00,  1.65255768e-01,  8.09560087e+03,
        1.62386778e+03,  4.73590447e+01,  2.29735335e+01,  9.38796718e+00,
        2.98559435e+01,  7.92997092e+01,  8.39680141e+01, -2.48064534e+01,
        7.32863374e+01,  4.88868408e+01,  5.85560387e+01])

In [17]:
house=model.predict([[70,85,12000,6,8,100,520,430,1024,950,850,1800,700,150,42]])
house

array([219696.36904045])

In [18]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(x1, y1, test_size = 0.25, random_state=0)

In [19]:
from sklearn.linear_model import LinearRegression
lin_reg_mod = LinearRegression()
lin_reg_mod.fit(X1_train, y1_train)

LinearRegression()

In [21]:
pred = lin_reg_mod.predict(X1_test)
pred

array([100212.13951268, 162361.70095778, 258052.4005472 , 169839.95820108,
       109017.5165217 , 180333.33864283, 100641.98784044, 221430.91705674,
       222596.82410993, 149597.21924243, 117111.80687596, 218229.37922961,
       341928.16515755, 168354.12960485, 197694.0173465 , 253914.67858693,
       121952.13169696, 200683.62836471, 128386.86537668,  96547.70162494,
       169382.44072569, 184304.9251493 , 150741.56942364, 163378.07067669,
       189353.98635029, 207584.96724356, 201192.93326243,  75800.37555707,
       235754.59892216, 201168.64654963, 282613.00474524, 192710.53620389,
       137449.1956226 , 265444.38884026, 121455.4857672 , 135863.03288609,
        90027.08353817, 149311.17505845, 135477.29248523,  99310.01471835,
       196087.88766155, 139733.56338756, 133602.57948928,  76729.14012142,
       198470.99921424, 231459.97072044,  80831.1823594 , 133032.86537346,
       109253.50473008, 198229.37017955, 101805.76539243, 201183.20060692,
       315896.41443068, 1

In [22]:
import numpy as np
from sklearn import metrics
test_set_r2 = metrics.r2_score(y1_test, pred)
print(test_set_r2)

0.7630222164561855


In [23]:
lin_reg_mod.predict([[70,85,12000,6,8,100,520,430,1024,950,850,1800,700,150,42]])

array([221263.24355059])

In [63]:
data = {'name':["raj","gree","pushp","shrav","anush","supriya","kaluu","sai","mano","tej"],
        'height':[154,158,162,177,182,168,166,177,154,158],
        'weight':[67,69,71,77,79,73,72,77,67,69],
        'location':["hyd","mum","chen","tn","bangl","srkl","odisa","delhi","goa","kerala"]}
df_data = pd.DataFrame(data)

In [104]:
df_data

name  height  weight location   bp
0      raj     154      67      hyd   97
1     gree     158      69      mum   99
2    pushp     162      71     chen  101
3    shrav     177      77       tn  107
4    anush     182      79    bangl  109
5  supriya     168      73     srkl  103
6    kaluu     166      72    odisa  102
7      sai     177      77    delhi  107
8     mano     154      67      goa   97
9      tej     158      69   kerala   99

In [105]:
x =df_data[['height']]

In [106]:
x

height
0     154
1     158
2     162
3     177
4     182
5     168
6     166
7     177
8     154
9     158

In [107]:
y = df_data['weight']

In [108]:
y

0    67
1    69
2    71
3    77
4    79
5    73
6    72
7    77
8    67
9    69
Name: weight, dtype: int64

In [109]:
from sklearn.linear_model import LinearRegression

In [110]:
model=LinearRegression()

In [111]:
model.fit(x,y)

LinearRegression()

In [112]:
model.score(x,y)

0.9977813388115342

In [113]:
model.predict([[154]])

array([67.16838267])

In [124]:
df_data.insert(4,'BP',[97,99,101,107,109,103,102,107,97,99])

In [116]:
df_data

name  height  weight location   bp
0      raj     154      67      hyd   97
1     gree     158      69      mum   99
2    pushp     162      71     chen  101
3    shrav     177      77       tn  107
4    anush     182      79    bangl  109
5  supriya     168      73     srkl  103
6    kaluu     166      72    odisa  102
7      sai     177      77    delhi  107
8     mano     154      67      goa   97
9      tej     158      69   kerala   99

In [125]:
x = df_data[['height','BP']]

In [126]:
model.fit(x,y)

LinearRegression()

In [127]:
model.score(x,y)

1.0

In [128]:
model.predict([[154,97]])

array([67.])